#!/usr/bin/env python3
"""Generate themes-index.md and corpus-report.md from the notes' frontmatter.

Usage: python3 tools/build_index.py
Idempotent: fully regenerates both files at the repository root.
"""
import os
import re
import glob
import unicodedata
from collections import defaultdict

# kb_common is a sibling module (tools/), importable in bare python3: its top-level
# imports (os/re/glob) are lightweight; numpy is only loaded inside cosine().
# pyright: reportMissingImports=false
from kb_common import parse_frontmatter, themes_fiche, objectives_fiche, OBJECTIVES

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIKI = os.path.join(ROOT, "wiki")
FICHES = os.path.join(WIKI, "concepts")
FICHES_OUTILS = os.path.join(WIKI, "tools")
THEME_DIR = os.path.join(WIKI, "themes")
GUIDES_DIR = os.path.join(WIKI, "guides")

# Pedagogical traversal order + displayed label per theme.
THEMES = [
    ("agent-fundamentals", "🧱 Agent fundamentals"),
    ("reasoning-planning", "🧠 Reasoning & planning"),
    ("prompting", "✍️ Prompting"),
    ("tools-function-calling", "🔧 Tools & function calling"),
    ("rag-context", "📚 RAG & context"),
    ("memory", "💾 Memory"),
    ("multi-agent", "👥 Multi-agent"),
    ("interop-protocols", "🔌 Interop protocols"),
    ("frameworks-tooling", "🛠️ Frameworks & tooling"),
    ("evaluation", "📊 Evaluation"),
    ("benchmarks", "🏁 Benchmarks"),
    ("security", "🔐 Security"),
    ("efficiency-cost", "⚡ Efficiency & cost"),
    ("governance-alignment-ops", "⚖️ Governance, alignment & ops"),
]
THEME_LABEL = dict(THEMES)
NIVEAU_RANG = {"🔴": 0, "🟡": 1, "🟢": 2}
NIVEAU_LABEL = [("🔴", "Substance / core"), ("🟡", "Tradeoff / intermediate"), ("🟢", "Overview / introductory")]

# One-line intro per theme, shown at the top of each theme page (L2).
THEME_INTRO = {
    "agent-fundamentals": "What an agent is, its components and its structural limits.",
    "reasoning-planning": "Making a model reason, plan and self-correct.",
    "prompting": "Crafting and optimizing prompts (techniques, in-context learning).",
    "tools-function-calling": "Giving an agent tools and refining the agent-computer interface.",
    "rag-context": "Augmenting the model through retrieval and managing context.",
    "memory": "Short/long-term memory and persistence across sessions.",
    "multi-agent": "Orchestrating and structuring multiple agents.",
    "interop-protocols": "Interoperability standards (MCP, A2A…).",
    "frameworks-tooling": "Frameworks and libraries for building agents.",
    "evaluation": "Measuring quality: evals, LLM judges, error analysis.",
    "benchmarks": "Test sets and standardized metrics.",
    "security": "Threats, injections and defense of LLM systems.",
    "efficiency-cost": "Reducing cost and latency (routing, caching, decoding).",
    "governance-alignment-ops": "Steering, observing and governing systems in production.",
}


def charger():
    fiches = []
    for f in sorted(glob.glob(os.path.join(FICHES, "*.md"))):
        d = parse_frontmatter(f)
        d["_slug"] = os.path.basename(f)[:-3]
        fiches.append(d)
    return fiches


def charger_outils():
    """Load the frontmatter of the tool notes (excluding `_*.md` templates)."""
    outils = []
    for f in sorted(glob.glob(os.path.join(FICHES_OUTILS, "*.md"))):
        if os.path.basename(f).startswith("_"):
            continue
        d = parse_frontmatter(f)
        d["_slug"] = os.path.basename(f)[:-3]
        d["_themes"] = themes_fiche(d)
        outils.append(d)
    return outils


def ligne_fiche(d, base="concepts/"):
    titre = d.get("title", d["_slug"])
    url = d.get("source_url", "").strip()
    src = f" → [source]({url})" if url else " → ⚠️ _missing source_"
    prim = d.get("primary_source", "").strip()
    prim = f"  ·  paper: {prim}" if prim else ""
    niv = d.get("level", "")
    return f"- {niv} **[{titre}]({base}{d['_slug']}.md)**{src}{prim}"


def ligne_outil(d, base="../tools/"):
    titre = d.get("title", d.get("tool", d["_slug"]))
    typ = d.get("type", "").strip()
    typ = f" — _{typ}_" if typ else ""
    cible = (base + d["_slug"] + ".md").replace(" ", "%20")
    return f"- **[{titre}]({cible})**{typ}"


def accroche_fiche(slug):
    """Extract the "In one sentence" hook from the body of a concept note. '' if absent."""
    try:
        txt = open(os.path.join(FICHES, slug + ".md"), encoding="utf-8", errors="replace").read()
    except OSError:
        return ""
    m = re.search(r"\*\*In one sentence\*\*\s*[—–-]\s*(.+)", txt)
    return m.group(1).strip() if m else ""


def rendu_bloc_guide(obj, items):
    """Render the index (grouped by theme) of the fiches tagged with a given objective."""
    par_theme = defaultdict(list)
    for d in items:
        par_theme[d.get("theme", "??")].append(d)
    lignes = [
        f"> ⚙️ **Generated index** — {len(items)} concept(s) tagged `objectives: [{obj}]`, "
        "regenerated by `tools/build_index.py`. The prose above is hand-curated.",
    ]
    for slug, label in THEMES:
        grp = par_theme.get(slug, [])
        if not grp:
            continue
        grp.sort(key=lambda d: (NIVEAU_RANG.get(d.get("level"), 9), d.get("title", "")))
        lignes.append(f"\n### {label}")
        for d in grp:
            acc = accroche_fiche(d["_slug"])
            acc = f" — {acc}" if acc else ""
            niv = d.get("level", "")
            lignes.append(f"- {niv} **[{d.get('title', d['_slug'])}](../concepts/{d['_slug']}.md)**{acc}")
    return "\n".join(lignes)


def slug_ascii(s):
    """ASCII kebab slug (for family anchors), accents stripped."""
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()


def ligne_outil_table(d):
    """Table row of a tool, rebuilt from its frontmatter."""
    titre = d.get("title", d.get("tool", d["_slug"]))
    url = d.get("url", "").strip()
    nom = f"**[{titre}]({url})**" if url else f"**{titre}**"
    fiche = f'[📄](../tools/{d["_slug"]}.md)'
    return (f"| {nom} · {fiche} | {d.get('type', '')} | {d.get('eco_icons', '')} "
            f"| {d.get('llm_cost_icons', '')} | {d.get('summary', '')} |")


_FAMILLES_META = None


def familles_meta():
    """Curated prose per family (intro + notes), source `tools/families.json`."""
    global _FAMILLES_META
    if _FAMILLES_META is None:
        import json
        p = os.path.join(ROOT, "tools", "families.json")
        _FAMILLES_META = json.load(open(p, encoding="utf-8")) if os.path.exists(p) else {}
    return _FAMILLES_META


def rendu_bloc_outils(obj, outils):
    """Render the tools of an objective, grouped by family (tables), from the frontmatter.

    Each family's curated prose (intro + "reading keys") is re-injected
    from `tools/families.json` — preserved, not lost with the censuses.
    """
    meta = familles_meta()
    par_fam = defaultdict(list)
    for d in outils:
        if obj in objectives_fiche(d):
            par_fam[d.get("family", "(sans famille)")].append(d)
    if not par_fam:
        return "> _(no tool linked to this objective yet)_"
    total = sum(len(v) for v in par_fam.values())
    lignes = [f"> ⚙️ **Generated tools** — {total} tool(s) `objectives: [{obj}]`, grouped by family. "
              "Regenerated by `tools/build_index.py` from the tool notes' frontmatter."]
    for fam in sorted(par_fam):
        lignes.append(f'\n<a id="fam-{slug_ascii(fam)}"></a>')
        lignes.append(f"### {fam}\n")
        if meta.get(fam):
            lignes.append(meta[fam] + "\n")
        lignes.append("| Tool | Type | Eco | LLM cost | Summary |")
        lignes.append("|---|---|:--:|:--:|---|")
        for d in sorted(par_fam[fam], key=lambda d: d.get("title", d["_slug"]).lower()):
            lignes.append(ligne_outil_table(d))
    return "\n".join(lignes)


def _injecter_bloc(txt, marqueur, bloc):
    """Replace the content between `<!-- marqueur -->` and `<!-- /marqueur -->` (append if absent)."""
    debut, fin = f"<!-- {marqueur} -->", f"<!-- /{marqueur.split(':')[0]} -->"
    remplacement = f"{debut}\n{bloc}\n{fin}"
    motif = re.compile(re.escape(debut) + r".*?" + re.escape(fin), re.DOTALL)
    return motif.sub(remplacement, txt) if motif.search(txt) else txt.rstrip() + "\n\n" + remplacement + "\n"


def build_guides(fiches, outils):
    """Fill the generated blocks of each subject page: concepts (`AUTO:objectif=X`)
    AND tools (`AUTO-OUTILS:objectif=X`). The curated prose is preserved.
    """
    if not os.path.isdir(GUIDES_DIR):
        return []
    fiches_par_obj = defaultdict(list)
    for d in fiches:
        for o in objectives_fiche(d):
            fiches_par_obj[o].append(d)
    generes = []
    for path in sorted(glob.glob(os.path.join(GUIDES_DIR, "*.md"))):
        txt = open(path, encoding="utf-8", errors="replace").read()
        obj = parse_frontmatter(txt).get("objective", "").strip()
        if not obj:
            continue
        if obj not in OBJECTIVES:
            sys_warn(f"⚠️  guide {os.path.basename(path)} : objective « {obj} » hors vocabulaire OBJECTIVES")
        txt = _injecter_bloc(txt, f"AUTO:objective={obj}", rendu_bloc_guide(obj, fiches_par_obj.get(obj, [])))
        txt = _injecter_bloc(txt, f"AUTO-OUTILS:objective={obj}", rendu_bloc_outils(obj, outils))
        open(path, "w", encoding="utf-8").write(txt)
        generes.append(os.path.basename(path)[:-3])
    return generes


def lister_guides():
    """[(slug, title)] of the present L3 guides, for the INDEX-THEMATIQUE summary."""
    res = []
    for path in sorted(glob.glob(os.path.join(GUIDES_DIR, "*.md"))):
        fm = parse_frontmatter(path)
        res.append((os.path.basename(path)[:-3], fm.get("title", os.path.basename(path)[:-3])))
    return res


def sys_warn(msg):
    import sys
    sys.stderr.write(msg + "\n")


def bloc_concepts_moc(concepts):
    """Render the concepts of a theme grouped by level, with hook (enriched L2)."""
    par_niv = defaultdict(list)
    for d in concepts:
        par_niv[d.get("level", "")].append(d)
    out = []
    for niv, lab in NIVEAU_LABEL:
        grp = sorted(par_niv.get(niv, []), key=lambda d: d.get("title", ""))
        if not grp:
            continue
        out.append(f"### {niv} {lab}")
        for d in grp:
            acc = accroche_fiche(d["_slug"])
            acc = f" — {acc}" if acc else ""
            out.append(f"- **[{d.get('title', d['_slug'])}](../concepts/{d['_slug']}.md)**{acc}")
        out.append("")
    return out or ["- _(aucun)_", ""]


def build_moc(fiches, outils):
    """Generate one hub page per theme: concepts + tools of the same subject.

    The links to `fiches/` and `fiches outils/` create, in the Obsidian graph,
    the edges that connect the two corpora through each theme.
    """
    os.makedirs(THEME_DIR, exist_ok=True)
    concepts_par_theme = defaultdict(list)
    for d in fiches:
        concepts_par_theme[d.get("theme", "??")].append(d)
    outils_par_theme = defaultdict(list)
    for d in outils:
        for th in d["_themes"]:
            outils_par_theme[th].append(d)

    generes = []
    for slug, label in THEMES:
        concepts = concepts_par_theme.get(slug, [])
        tools = outils_par_theme.get(slug, [])
        tools.sort(key=lambda d: d.get("title", d["_slug"]).lower())
        nom = label.split(" ", 1)[1]
        out = [
            "---", "type: index", f'title: "Theme — {nom}"', f"theme: {slug}", "---", "",
            f"# {label}", "",
            "> ⚙️ **Generated file** by `tools/build_index.py` — do not edit by hand.", "",
        ]
        intro = THEME_INTRO.get(slug)
        if intro:
            out += [f"_{intro}_", ""]
        out += [f"## Concepts ({len(concepts)})", ""]
        out += bloc_concepts_moc(concepts)
        out += [f"## Tools ({len(tools)})", ""]
        out += [ligne_outil(d) for d in tools] or ["- _(aucun)_"]
        open(os.path.join(THEME_DIR, f"{slug}.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
        generes.append(slug)
    return generes


def build_index(fiches, outils):
    """themes-index.md: lightweight summary pointing to the per-theme pages."""
    concepts_par_theme = defaultdict(list)
    for d in fiches:
        concepts_par_theme[d.get("theme", "??")].append(d)
    outils_par_theme = defaultdict(list)
    for d in outils:
        for th in d["_themes"]:
            outils_par_theme[th].append(d)
    out = ["# Thematic index of the AI corpus\n",
           "> ⚙️ **Generated file** by `tools/build_index.py` — do not edit by hand.\n",
           f"{len(fiches)} concepts · {len(outils)} tools · "
           "each theme opens a hub page (concepts + tools).\n"]
    guides = lister_guides()
    if guides:
        out.append("## Guides by objective (cross-cutting)\n")
        out += [f"- **[{titre}](guides/{slug}.md)**" for slug, titre in guides]
        out.append("")
    out += ["## By theme\n",
            "| Theme | Concepts | Tools |",
            "|---|---:|---:|"]
    for slug, label in THEMES:
        nc = len(concepts_par_theme.get(slug, []))
        no = len(outils_par_theme.get(slug, []))
        out.append(f"| [{label}](themes/{slug}.md) | {nc} | {no} |")
    autres = sorted(k for k in concepts_par_theme if k not in THEME_LABEL)
    if autres:
        out.append("")
        for slug in autres:
            items = concepts_par_theme[slug]
            out.append(f"\n## ⚠️ {slug} (off-taxonomy theme)\n")
            out += [ligne_fiche(d) for d in items]
    open(os.path.join(WIKI, "themes-index.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")


def build_rapport(fiches, outils):
    par_theme = defaultdict(list)
    sans_url = []
    for d in fiches:
        par_theme[d.get("theme", "??")].append(d)
        if not d.get("source_url", "").strip():
            sans_url.append(d["_slug"])
    out = ["# Corpus completeness report\n",
           "> ⚙️ **Generated file** by `tools/build_index.py`.\n",
           f"**{len(fiches)} concepts** total.\n",
           "## By theme\n"]
    for slug, label in THEMES:
        n = len(par_theme.get(slug, []))
        flag = "  ⚠️ _thin coverage_" if n < 3 else ""
        out.append(f"- {label} : {n}{flag}")
    out.append(f"\n## Concepts without `source_url` ({len(sans_url)})\n")
    out += [f"- `{s}`" for s in sorted(sans_url)] or ["- (none)"]
    # possible title duplicates
    par_titre = defaultdict(list)
    for d in fiches:
        par_titre[d.get("title", "").lower()].append(d["_slug"])
    dups = {t: s for t, s in par_titre.items() if len(s) > 1}
    out.append(f"\n## Potential title duplicates ({len(dups)})\n")
    out += [f"- « {t} » : {', '.join(s)}" for t, s in dups.items()] or ["- (none)"]

    sans, hors = valider_themes_outils(outils)
    out.append(f"\n## Tools without `themes` ({len(sans)})\n")
    out += [f"- `{s}`" for s in sorted(sans)] or ["- (none)"]
    out.append(f"\n## Tools with an off-taxonomy theme ({len(hors)})\n")
    out += [f"- `{s}` : {', '.join(t)}" for s, t in sorted(hors.items())] or ["- (none)"]
    open(os.path.join(WIKI, "corpus-report.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")


def valider_themes_outils(outils):
    """List the tools whose `themes` is empty or contains an off-taxonomy theme."""
    valides = set(THEME_LABEL)
    sans = [d["_slug"] for d in outils if not d["_themes"]]
    hors = {d["_slug"]: [t for t in d["_themes"] if t not in valides]
            for d in outils}
    hors = {s: t for s, t in hors.items() if t}
    return sans, hors


def build_okf_index(fiches):
    """Generate index.md at the root: OKF entry point (progressive disclosure).

    Does not duplicate the content — points to the existing indexes/tables/hub.
    """
    n_concepts = len(fiches)
    n_outils = len(glob.glob(os.path.join(WIKI, "tools", "*.md")))
    n_outils = max(0, n_outils - len(glob.glob(os.path.join(WIKI, "tools", "_*.md"))))
    out = [
        "---",
        'type: index',
        'title: "AI Corpus — Knowledge Base"',
        'description: "Point d\'entrée OKF du wiki : concepts (concepts/) + recensement d\'outils (tools/)."',
        "---",
        "",
        "# AI corpus — entry point",
        "",
        "> ⚙️ **Generated file** by `tools/build_index.py` — do not edit by hand.",
        "> [Open Knowledge Format](https://okf.md/spec/)-compliant bundle; the authoritative schema is `process/SCHEMA.md` (strict superset).",
        "",
        "## Contents",
        "",
        *([f"- **Guides by objective** ({len(lister_guides())}) → [`guides/`](guides/) "
           "· cross-cutting, task-oriented paths"] if lister_guides() else []),
        f"- **Concepts** ({n_concepts}) → [`concepts/`](concepts/) · index: [themes-index.md](themes-index.md)",
        f"- **Tools** ({n_outils}) → [`tools/`](tools/) · hub & legend: [tools-hub.md](tools-hub.md)",
        "  - by subject: [generate code with AI](guides/generate-code-with-ai.md) · "
        "[AI in production](guides/ai-in-production.md) · "
        "[AI for non-coders](guides/ai-for-non-coders.md)",
        "",
        "## Reserved files (OKF)",
        "",
        "- [index.md](index.md) — this file (bundle listing)",
        "- [log.md](log.md) — append-only journal, newest at the bottom",
        "",
        "## Generated derivatives",
        "",
        "- [themes-index.md](themes-index.md) — themes summary (concepts + tools)",
        "- [`themes/`](themes/) — one hub page per theme, linking concepts and tools",
        "- [corpus-report.md](corpus-report.md) — completeness / duplicates / tool themes",
    ]
    open(os.path.join(WIKI, "index.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")


def main():
    import sys
    fiches = charger()
    outils = charger_outils()
    mocs = build_moc(fiches, outils)
    guides = build_guides(fiches, outils)
    build_index(fiches, outils)
    build_rapport(fiches, outils)
    build_okf_index(fiches)
    sys.stdout.write(f"OK — {len(fiches)} concepts + {len(outils)} outils indexés.\n")
    sys.stdout.write(f"→ {len(mocs)} themes/*.md\n→ {len(guides)} guide(s) L3\n→ themes-index.md\n"
                     "→ corpus-report.md\n→ index.md (OKF)\n")


if __name__ == "__main__":
    main()
