#!/usr/bin/env python3
"""Generate themes-index.md and corpus-report.md from the notes' frontmatter.

Usage: python3 tools/build_index.py
Idempotent: fully regenerates both files at the repository root.
"""
import os
import re
import glob
import unicodedata
from collections import defaultdict

# kb_common is a sibling module (tools/), importable in bare python3: its top-level
# imports (os/re/glob) are lightweight; numpy is only loaded inside cosine().
# pyright: reportMissingImports=false
from kb_common import parse_frontmatter, note_themes, note_objectives, OBJECTIVES

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIKI = os.path.join(ROOT, "wiki")
CONCEPTS = os.path.join(WIKI, "concepts")
TOOLS = os.path.join(WIKI, "tools")
THEME_DIR = os.path.join(WIKI, "themes")
GUIDES_DIR = os.path.join(WIKI, "guides")

# Pedagogical traversal order + displayed label per theme.
THEMES = [
    ("agent-fundamentals", "🧱 Agent fundamentals"),
    ("reasoning-planning", "🧠 Reasoning & planning"),
    ("prompting", "✍️ Prompting"),
    ("tools-function-calling", "🔧 Tools & function calling"),
    ("rag-context", "📚 RAG & context"),
    ("memory", "💾 Memory"),
    ("multi-agent", "👥 Multi-agent"),
    ("interop-protocols", "🔌 Interop protocols"),
    ("frameworks-tooling", "🛠️ Frameworks & tooling"),
    ("evaluation", "📊 Evaluation"),
    ("benchmarks", "🏁 Benchmarks"),
    ("security", "🔐 Security"),
    ("efficiency-cost", "⚡ Efficiency & cost"),
    ("governance-alignment-ops", "⚖️ Governance, alignment & ops"),
]
THEME_LABEL = dict(THEMES)
LEVEL_RANK = {"🔴": 0, "🟡": 1, "🟢": 2}
LEVEL_LABEL = [("🔴", "Substance / core"), ("🟡", "Tradeoff / intermediate"), ("🟢", "Overview / introductory")]

# One-line intro per theme, shown at the top of each theme page (L2).
THEME_INTRO = {
    "agent-fundamentals": "What an agent is, its components and its structural limits.",
    "reasoning-planning": "Making a model reason, plan and self-correct.",
    "prompting": "Crafting and optimizing prompts (techniques, in-context learning).",
    "tools-function-calling": "Giving an agent tools and refining the agent-computer interface.",
    "rag-context": "Augmenting the model through retrieval and managing context.",
    "memory": "Short/long-term memory and persistence across sessions.",
    "multi-agent": "Orchestrating and structuring multiple agents.",
    "interop-protocols": "Interoperability standards (MCP, A2A…).",
    "frameworks-tooling": "Frameworks and libraries for building agents.",
    "evaluation": "Measuring quality: evals, LLM judges, error analysis.",
    "benchmarks": "Test sets and standardized metrics.",
    "security": "Threats, injections and defense of LLM systems.",
    "efficiency-cost": "Reducing cost and latency (routing, caching, decoding).",
    "governance-alignment-ops": "Steering, observing and governing systems in production.",
}


def load_notes_fm():
    notes = []
    for f in sorted(glob.glob(os.path.join(CONCEPTS, "*.md"))):
        d = parse_frontmatter(f)
        d["_slug"] = os.path.basename(f)[:-3]
        notes.append(d)
    return notes


def load_tools_fm():
    """Load the frontmatter of the tool notes (excluding `_*.md` templates)."""
    tools = []
    for f in sorted(glob.glob(os.path.join(TOOLS, "*.md"))):
        if os.path.basename(f).startswith("_"):
            continue
        d = parse_frontmatter(f)
        d["_slug"] = os.path.basename(f)[:-3]
        d["_themes"] = note_themes(d)
        tools.append(d)
    return tools


def note_line(d, base="concepts/"):
    title = d.get("title", d["_slug"])
    url = d.get("source_url", "").strip()
    src = f" → [source]({url})" if url else " → ⚠️ _missing source_"
    paper = d.get("primary_source", "").strip()
    paper = f"  ·  paper: {paper}" if paper else ""
    level_icon = d.get("level", "")
    return f"- {level_icon} **[{title}]({base}{d['_slug']}.md)**{src}{paper}"


def tool_line(d, base="../tools/"):
    title = d.get("title", d.get("tool", d["_slug"]))
    typ = d.get("type", "").strip()
    typ = f" — _{typ}_" if typ else ""
    target = (base + d["_slug"] + ".md").replace(" ", "%20")
    return f"- **[{title}]({target})**{typ}"


def note_hook(slug):
    """Extract the "In one sentence" hook from the body of a concept note. '' if absent."""
    try:
        txt = open(os.path.join(CONCEPTS, slug + ".md"), encoding="utf-8", errors="replace").read()
    except OSError:
        return ""
    m = re.search(r"\*\*In one sentence\*\*\s*[—–-]\s*(.+)", txt)
    return m.group(1).strip() if m else ""


def render_concept_block(obj, items):
    """Render the index (grouped by theme) of the notes tagged with a given objective."""
    by_theme = defaultdict(list)
    for d in items:
        by_theme[d.get("theme", "??")].append(d)
    lines = [
        f"> ⚙️ **Generated index** — {len(items)} concept(s) tagged `objectives: [{obj}]`, "
        "regenerated by `tools/build_index.py`. The prose above is hand-curated.",
    ]
    for slug, label in THEMES:
        grp = by_theme.get(slug, [])
        if not grp:
            continue
        grp.sort(key=lambda d: (LEVEL_RANK.get(d.get("level"), 9), d.get("title", "")))
        lines.append(f"\n### {label}")
        for d in grp:
            hook = note_hook(d["_slug"])
            hook = f" — {hook}" if hook else ""
            level_icon = d.get("level", "")
            lines.append(f"- {level_icon} **[{d.get('title', d['_slug'])}](../concepts/{d['_slug']}.md)**{hook}")
    return "\n".join(lines)


def slug_ascii(s):
    """ASCII kebab slug (for family anchors), accents stripped."""
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()


def tool_row(d):
    """Table row of a tool, rebuilt from its frontmatter."""
    title = d.get("title", d.get("tool", d["_slug"]))
    url = d.get("url", "").strip()
    name = f"**[{title}]({url})**" if url else f"**{title}**"
    note = f'[📄](../tools/{d["_slug"]}.md)'
    return (f"| {name} · {note} | {d.get('type', '')} | {d.get('eco_icons', '')} "
            f"| {d.get('llm_cost_icons', '')} | {d.get('summary', '')} |")


_FAMILIES_META = None


def families_meta():
    """Curated prose per family (intro + notes), source `tools/families.json`."""
    global _FAMILIES_META
    if _FAMILIES_META is None:
        import json
        p = os.path.join(ROOT, "tools", "families.json")
        _FAMILIES_META = json.load(open(p, encoding="utf-8")) if os.path.exists(p) else {}
    return _FAMILIES_META


def render_tools_block(obj, tools):
    """Render the tools of an objective, grouped by family (tables), from the frontmatter.

    Each family's curated prose (intro + "reading keys") is re-injected
    from `tools/families.json` — preserved, not lost with the censuses.
    """
    meta = families_meta()
    by_fam = defaultdict(list)
    for d in tools:
        if obj in note_objectives(d):
            by_fam[d.get("family", "(no family)")].append(d)
    if not by_fam:
        return "> _(no tool linked to this objective yet)_"
    total = sum(len(v) for v in by_fam.values())
    lines = [f"> ⚙️ **Generated tools** — {total} tool(s) `objectives: [{obj}]`, grouped by family. "
             "Regenerated by `tools/build_index.py` from the tool notes' frontmatter."]
    for fam in sorted(by_fam):
        lines.append(f'\n<a id="fam-{slug_ascii(fam)}"></a>')
        lines.append(f"### {fam}\n")
        if meta.get(fam):
            lines.append(meta[fam] + "\n")
        lines.append("| Tool | Type | Eco | LLM cost | Summary |")
        lines.append("|---|---|:--:|:--:|---|")
        for d in sorted(by_fam[fam], key=lambda d: d.get("title", d["_slug"]).lower()):
            lines.append(tool_row(d))
    return "\n".join(lines)


def _inject_block(txt, marker, block):
    """Replace the content between `<!-- marker -->` and `<!-- /marker -->` (append if absent)."""
    start, end = f"<!-- {marker} -->", f"<!-- /{marker.split(':')[0]} -->"
    replacement = f"{start}\n{block}\n{end}"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    return pattern.sub(replacement, txt) if pattern.search(txt) else txt.rstrip() + "\n\n" + replacement + "\n"


def build_guides(notes, tools):
    """Fill the generated blocks of each subject page: concepts (`AUTO:objective=X`)
    AND tools (`AUTO-TOOLS:objective=X`). The curated prose is preserved.
    """
    if not os.path.isdir(GUIDES_DIR):
        return []
    notes_by_obj = defaultdict(list)
    for d in notes:
        for o in note_objectives(d):
            notes_by_obj[o].append(d)
    generated = []
    for path in sorted(glob.glob(os.path.join(GUIDES_DIR, "*.md"))):
        txt = open(path, encoding="utf-8", errors="replace").read()
        obj = parse_frontmatter(txt).get("objective", "").strip()
        if not obj:
            continue
        if obj not in OBJECTIVES:
            sys_warn(f"⚠️  guide {os.path.basename(path)}: objective '{obj}' outside the OBJECTIVES vocabulary")
        txt = _inject_block(txt, f"AUTO:objective={obj}", render_concept_block(obj, notes_by_obj.get(obj, [])))
        txt = _inject_block(txt, f"AUTO-TOOLS:objective={obj}", render_tools_block(obj, tools))
        open(path, "w", encoding="utf-8").write(txt)
        generated.append(os.path.basename(path)[:-3])
    return generated


def list_guides():
    """[(slug, title)] of the present L3 guides, for the INDEX-THEMATIQUE summary."""
    res = []
    for path in sorted(glob.glob(os.path.join(GUIDES_DIR, "*.md"))):
        fm = parse_frontmatter(path)
        res.append((os.path.basename(path)[:-3], fm.get("title", os.path.basename(path)[:-3])))
    return res


def sys_warn(msg):
    import sys
    sys.stderr.write(msg + "\n")


def concept_block(concepts):
    """Render the concepts of a theme grouped by level, with hook (enriched L2)."""
    by_level = defaultdict(list)
    for d in concepts:
        by_level[d.get("level", "")].append(d)
    out = []
    for niv, lab in LEVEL_LABEL:
        grp = sorted(by_level.get(niv, []), key=lambda d: d.get("title", ""))
        if not grp:
            continue
        out.append(f"### {niv} {lab}")
        for d in grp:
            acc = note_hook(d["_slug"])
            acc = f" — {acc}" if acc else ""
            out.append(f"- **[{d.get('title', d['_slug'])}](../concepts/{d['_slug']}.md)**{acc}")
        out.append("")
    return out or ["- _(none)_", ""]


def build_theme_pages(notes, tools):
    """Generate one hub page per theme: concepts + tools of the same subject.

    The links to `concepts/` and `tools/` create, in the Obsidian graph,
    the edges that connect the two corpora through each theme.
    """
    os.makedirs(THEME_DIR, exist_ok=True)
    concepts_by_theme = defaultdict(list)
    for d in notes:
        concepts_by_theme[d.get("theme", "??")].append(d)
    tools_by_theme = defaultdict(list)
    for d in tools:
        for th in d["_themes"]:
            tools_by_theme[th].append(d)

    generated = []
    for slug, label in THEMES:
        concepts = concepts_by_theme.get(slug, [])
        theme_tools = tools_by_theme.get(slug, [])
        theme_tools.sort(key=lambda d: d.get("title", d["_slug"]).lower())
        name = label.split(" ", 1)[1]
        out = [
            "---", "type: index", f'title: "Theme — {name}"', f"theme: {slug}", "---", "",
            f"# {label}", "",
            "> ⚙️ **Generated file** by `tools/build_index.py` — do not edit by hand.", "",
        ]
        intro = THEME_INTRO.get(slug)
        if intro:
            out += [f"_{intro}_", ""]
        out += [f"## Concepts ({len(concepts)})", ""]
        out += concept_block(concepts)
        out += [f"## Tools ({len(theme_tools)})", ""]
        out += [tool_line(d) for d in theme_tools] or ["- _(none)_"]
        open(os.path.join(THEME_DIR, f"{slug}.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
        generated.append(slug)
    return generated


def build_index(notes, tools):
    """themes-index.md: lightweight summary pointing to the per-theme pages."""
    concepts_by_theme = defaultdict(list)
    for d in notes:
        concepts_by_theme[d.get("theme", "??")].append(d)
    tools_by_theme = defaultdict(list)
    for d in tools:
        for th in d["_themes"]:
            tools_by_theme[th].append(d)
    out = ["# Thematic index of the AI corpus\n",
           "> ⚙️ **Generated file** by `tools/build_index.py` — do not edit by hand.\n",
           f"{len(notes)} concepts · {len(tools)} tools · "
           "each theme opens a hub page (concepts + tools).\n"]
    guides = list_guides()
    if guides:
        out.append("## Guides by objective (cross-cutting)\n")
        out += [f"- **[{title}](guides/{slug}.md)**" for slug, title in guides]
        out.append("")
    out += ["## By theme\n",
            "| Theme | Concepts | Tools |",
            "|---|---:|---:|"]
    for slug, label in THEMES:
        nc = len(concepts_by_theme.get(slug, []))
        no = len(tools_by_theme.get(slug, []))
        out.append(f"| [{label}](themes/{slug}.md) | {nc} | {no} |")
    others = sorted(k for k in concepts_by_theme if k not in THEME_LABEL)
    if others:
        out.append("")
        for slug in others:
            items = concepts_by_theme[slug]
            out.append(f"\n## ⚠️ {slug} (off-taxonomy theme)\n")
            out += [note_line(d) for d in items]
    open(os.path.join(WIKI, "themes-index.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")


def build_report(notes, tools):
    by_theme = defaultdict(list)
    without_url = []
    for d in notes:
        by_theme[d.get("theme", "??")].append(d)
        if not d.get("source_url", "").strip():
            without_url.append(d["_slug"])
    out = ["# Corpus completeness report\n",
           "> ⚙️ **Generated file** by `tools/build_index.py`.\n",
           f"**{len(notes)} concepts** total.\n",
           "## By theme\n"]
    for slug, label in THEMES:
        n = len(by_theme.get(slug, []))
        flag = "  ⚠️ _thin coverage_" if n < 3 else ""
        out.append(f"- {label} : {n}{flag}")
    out.append(f"\n## Concepts without `source_url` ({len(without_url)})\n")
    out += [f"- `{s}`" for s in sorted(without_url)] or ["- (none)"]
    # possible title duplicates
    by_title = defaultdict(list)
    for d in notes:
        by_title[d.get("title", "").lower()].append(d["_slug"])
    duplicates = {t: s for t, s in by_title.items() if len(s) > 1}
    out.append(f"\n## Potential title duplicates ({len(duplicates)})\n")
    out += [f"- \"{t}\" : {', '.join(s)}" for t, s in duplicates.items()] or ["- (none)"]

    without_themes, off_taxonomy = validate_tool_themes(tools)
    out.append(f"\n## Tools without `themes` ({len(without_themes)})\n")
    out += [f"- `{s}`" for s in sorted(without_themes)] or ["- (none)"]
    out.append(f"\n## Tools with an off-taxonomy theme ({len(off_taxonomy)})\n")
    out += [f"- `{s}` : {', '.join(t)}" for s, t in sorted(off_taxonomy.items())] or ["- (none)"]
    open(os.path.join(WIKI, "corpus-report.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")


def validate_tool_themes(tools):
    """List the tools whose `themes` is empty or contains an off-taxonomy theme."""
    valid = set(THEME_LABEL)
    without_themes = [d["_slug"] for d in tools if not d["_themes"]]
    off_taxonomy = {d["_slug"]: [t for t in d["_themes"] if t not in valid]
                    for d in tools}
    off_taxonomy = {s: t for s, t in off_taxonomy.items() if t}
    return without_themes, off_taxonomy


def build_okf_index(notes):
    """Generate index.md at the root: OKF entry point (progressive disclosure).

    Does not duplicate the content — points to the existing indexes/tables/hub.
    """
    n_concepts = len(notes)
    n_tools = len(glob.glob(os.path.join(WIKI, "tools", "*.md")))
    n_tools = max(0, n_tools - len(glob.glob(os.path.join(WIKI, "tools", "_*.md"))))
    out = [
        "---",
        'type: index',
        'title: "AI Corpus — Knowledge Base"',
        'description: "OKF entry point of the wiki: concepts (concepts/) + tool census (tools/)."',
        "---",
        "",
        "# AI corpus — entry point",
        "",
        "> ⚙️ **Generated file** by `tools/build_index.py` — do not edit by hand.",
        "> [Open Knowledge Format](https://okf.md/spec/)-compliant bundle; the authoritative schema is `process/SCHEMA.md` (strict superset).",
        "",
        "## Contents",
        "",
        *([f"- **Guides by objective** ({len(list_guides())}) → [`guides/`](guides/) "
           "· cross-cutting, task-oriented paths"] if list_guides() else []),
        f"- **Concepts** ({n_concepts}) → [`concepts/`](concepts/) · index: [themes-index.md](themes-index.md)",
        f"- **Tools** ({n_tools}) → [`tools/`](tools/) · hub & legend: [tools-hub.md](tools-hub.md)",
        "  - by subject: [generate code with AI](guides/generate-code-with-ai.md) · "
        "[AI in production](guides/ai-in-production.md) · "
        "[AI for non-coders](guides/ai-for-non-coders.md)",
        "",
        "## Reserved files (OKF)",
        "",
        "- [index.md](index.md) — this file (bundle listing)",
        "- [log.md](log.md) — append-only journal, newest at the bottom",
        "",
        "## Generated derivatives",
        "",
        "- [themes-index.md](themes-index.md) — themes summary (concepts + tools)",
        "- [`themes/`](themes/) — one hub page per theme, linking concepts and tools",
        "- [corpus-report.md](corpus-report.md) — completeness / duplicates / tool themes",
    ]
    open(os.path.join(WIKI, "index.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")


def main():
    import sys
    notes = load_notes_fm()
    tools = load_tools_fm()
    theme_pages = build_theme_pages(notes, tools)
    guides = build_guides(notes, tools)
    build_index(notes, tools)
    build_report(notes, tools)
    build_okf_index(notes)
    sys.stdout.write(f"OK — {len(notes)} concepts + {len(tools)} tools indexed.\n")
    sys.stdout.write(f"→ {len(theme_pages)} themes/*.md\n→ {len(guides)} guide(s) L3\n→ themes-index.md\n"
                     "→ corpus-report.md\n→ index.md (OKF)\n")


if __name__ == "__main__":
    main()
